Parameters: 
  Region: 'cn-hangzhou'
  Scence: 'key-auth-plugin'
  GatewayId: gw-cunbie6m1hkohjeuilrg
  EnvironmentId: env-cunbj26m1hkjrjddmljg
  Name: 'key-auth-plugin'
ScenceConfigs:
  - Name: 单机版
    NameEn: 'Single Service'
    Url: 'templates/msa.yaml'
    Parameters: 
      Backend:
        Cpu: 1
        Memory: 1024