Parameters: 
  Region: 'cn-hangzhou'
  Scence: 'key-auth-plugin'
  GatewayId: gw-cu9g7dem1hkn32ee70bg
  EnvironmentId: env-cu9g82mm1hkui0vcv5eg
  Name: 'key-auth-plugin'
ScenceConfigs:
  - Name: 单机版
    NameEn: 'Single Service'
    Url: 'templates/msa.yaml'
    Parameters: 
      Backend:
        Cpu: 2018
        Memory: 4096